services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - .env
      
  backend:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: npm run dev